### ISSUE TITLE
Regressors fails when collecting regressors

### ISSUE THREAD

**Issue by sama2689** [cutright/DVH-Analytics#167]
I am installing via pip on Windows 10 within a conda environment and am getting an error that the package cannot collect regressors

```
C:\Users\USER\Documents>pip install dvha
Collecting dvha
  Using cached dvha-0.9.7-py3-none-any.whl (1.2 MB)
Collecting pypubsub
  Using cached Pypubsub-4.0.3-py3-none-any.whl (61 kB)
Collecting bokeh<2.0.0,>=1.2.0
  Using cached bokeh-1.4.0.tar.gz (32.4 MB)
Requirement already satisfied: python-dateutil in c:\users\USER\anaconda3\envs\dvh38\lib\site-packages (from dvha) (2.8.2)
Collecting wxPython>=4.1.1
  Using cached wxPython-4.1.1-cp38-cp38-win_amd64.whl (18.1 MB)
Requirement already satisfied: shapely[vectorized] in c:\users\USER\anaconda3\envs\dvh38\lib\site-packages (from dvha) (1.7.1)
Collecting rapidfuzz
  Using cached rapidfuzz-1.6.2-cp38-cp38-win_amd64.whl (974 kB)
Requirement already satisfied: pydicom>=1.4.0 in c:\users\USER\anaconda3\envs\dvh38\lib\site-packages (from dvha) (2.2.1)
Collecting regressors
  Using cached regressors-0.0.3.tar.gz (24 kB)
    ERROR: Command errored out with exit status 1:

```

Indeed, I can't even seem to install the regressors package manually as this returns the error 

```
ERROR: Could not find a version that satisfies the requirement regressors (from versions: 0.0.1, 0.0.2, 0.0.3)
ERROR: No matching distribution found for regressors
```

I've had this issue now on both python 3.7 and 3.8. Have there been any recent changes to the package that might be causing this? I can't quite figure out why this might be happening.

Thanks

EDIT: Tried installing regressors by itself and that doesn't work either, and states that `error in regressors setup command: use_2to3 is invalid.` Issue can be resolved by downgrading setuptools to 50.3.2

**Comment by cutright** [comment]
No changes to DVHA and regressors doesn’t appear to have changed. Are you
on a new computer or OS by chance?

**Comment by sama2689** [comment]
Yes this is a new computer, the OS is still MSW10 though. Though I have tried from fresh environments.

**Comment by sama2689** [comment]
Checking the regressors PyPi page shows that it is not tested for Python>3.4. I suspect this could be the issue, but I don't understand then how dvha was sucessfully installed and run on 3.8 and 3.9 environments? The error when installing dvha is one in regressors itself, specifically `error in regressors setup command: use_2to3 is invalid.`

This seems to imply the issue is my python version, but again to the best of my knowledge dvha has been installed on 3.8 before so I am not sure what is special about my specific installation. I am not installing with admin rights, not sure if this could be a potential issue or not but I can't imagine how it would be.

**Comment by sama2689** [comment]
I have fixed the issue, it turns out that the problem was that I had the latest version of setuptools, but downgrading setuptools to 50.3.2 did the trick (`conda install -c anaconda setuptools=50.3.2` if using anaconda). This seems to be a known issue with setuptools but it could well cause issues when trying to install dvha using pip. After downgrading setuptools, `pip install regressors` works fine. and therefore so does `pip install dvha`

Also, setuptools was recently upgraded on conda, which is likely why my previous installations worked just fine (dvha was installed on my other computer months ago, well before the setuptools update, but installing dvha now created an issue)

**Comment by cutright** [comment]
Good find @sama2689 

I tried installing a package using `regressors` last week on an M1 Mac and I was unsuccessful. Unfortunately, downgrading setup tools to 50.3.2 didn't resolve the issue. At least in my case, the real culprit appears to be `statsmodels`, which `regressors` depends on. For any other M1 Mac users out there, I used [this trick](https://github.com/scipy/scipy/issues/13409#issue-790703815) to install `statsmodels` (just replace `scipy` with `statsmodels`). You may have to do the same with some other packages. Also note that the latest `scipy` dev has wheels for M1 (so you don't need this trick). Finally, do a regular `pip install regressors` after all of its dependencies are installed.
